### PR TITLE
Disable (and restore after scroll) relative line numbers to improve performance

### PR DESCRIPTION
**Pull request by airnomad**

### CODE REVIEW

**Comment by yonchu** [comment]
Hi, airnomad.

Thank you for your PR.
But, I think some of them want to enable relative line numbers while scrolling.

You can use autocmd like the followings to disable it instead.

``` vim
autocmd User AcSmoothScrollEnter set nu
autocmd User AcSmoothScrollLeave set rnu
```

**Comment by airnomad** [comment]
Yeah, that would work too.

I also noticed scrolling is much slower if I open multiple windows.

Thanks.

**Comment by yonchu** [comment]
> I also noticed scrolling is much slower if I open multiple windows.

Exactly.

I' ve merged your PR and added the option to disable it.
How is that?

**Comment by airnomad** [comment]
Tnx a lot.

I also noticed scrolling is much slower if I open multiple windows.

Exactly.

I' ve merged your PR and added the option to disable it.
How is that?

—
Reply to this email directly or view it on
GitHubhttps://github.com/yonchu/accelerated-smooth-scroll/pull/5#issuecomment-22246695
.

**Pull request merged**
